// Generated by delombok at Mon Feb 10 12:42:16 CST 2025
package com.eglobal.tools.parser.report.observer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.eglobal.tools.parser.report.dto.Report;

public class EventManager implements Observable {
    Map<EventType, List<EventListener>> listeners = new HashMap<>();

    public EventManager(EventType... eventsType) {
        for (EventType eventType : eventsType) {
            this.listeners.put(eventType, new ArrayList<>());
        }
    }

    @Override
    public synchronized void suscribe(EventType eventType, EventListener eventListener) {
        java.util.List<com.eglobal.tools.parser.report.observer.EventListener> listener = listeners.get(eventType);
        listener.add(eventListener);
    }

    @Override
    public synchronized void unsuscribe(EventType eventType, EventListener eventListener) {
        java.util.List<com.eglobal.tools.parser.report.observer.EventListener> listener = listeners.get(eventType);
        listener.remove(eventListener);
    }

    @Override
    public synchronized void notify(EventType eventType, Report data) {
        java.util.List<com.eglobal.tools.parser.report.observer.EventListener> listener = listeners.get(eventType);
        for (EventListener eventListener : listener) {
            eventListener.update(eventType, data);
        }
    }
}
