// Generated by delombok at Mon Feb 10 12:45:11 CST 2025
package com.eglobal.tools.analytics.category.interfaces;

import com.eglobal.tools.analytics.category.interfaces.pojo.FieldValue;
import com.google.gson.Gson;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * @author egldt1029
 */
public abstract class AInterfaceLoader {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AInterfaceLoader.class);
    protected Map<String, FieldValue> fields = new HashMap<>();

    protected void init(String resource) {
    	File file = new File(resource);
		URL url = null;
		try {
			if(file.exists()) {
				url = file.toURI().toURL();
			} else {
				log.error("No se encontro el recurso " + resource);
				return;
			}
		} catch (MalformedURLException e) {
			log.error("No se encontro el recurso " + resource);
			return;
		}
    	
        try (InputStream is = url.openStream()) {
            java.util.Optional<java.io.InputStream> optInput = Optional.ofNullable(is);
            if (!optInput.isPresent()) {
                log.error("Recurso no encontrado: {}", resource);
                return;
            }
            try (InputStreamReader reader = new InputStreamReader(is)) {
                JSONParser jsonParser = new JSONParser();
                JSONArray jsonArray = (JSONArray) jsonParser.parse(reader);
                Gson gson = new Gson();
                for (Object object : jsonArray) {
                    JSONObject jsonObject = (JSONObject) object;
                    FieldValue fieldValue = gson.fromJson(jsonObject.toString(), FieldValue.class);
                    fields.put(fieldValue.getIndex(), fieldValue);
                }
            }
        } catch (IOException | ParseException exception) {
            log.error("Error al leer el recurso {}", resource, exception);
        }
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, FieldValue> getFields() {
        return this.fields;
    }
}
