// Generated by delombok at Mon Feb 10 12:47:07 CST 2025
package com.eglobal.tools.validation.statistics;

public class TransactionStatistics {
	private long counter;
	private long approved;
	private long declined;

	@java.lang.SuppressWarnings("all")
	public long getCounter() {
		return this.counter;
	}

	@java.lang.SuppressWarnings("all")
	public long getApproved() {
		return this.approved;
	}

	@java.lang.SuppressWarnings("all")
	public long getDeclined() {
		return this.declined;
	}
}
