// Generated by delombok at Mon Feb 10 12:47:06 CST 2025
package com.eglobal.tools.validation;

import java.awt.*;

public class Alert {
    private final String text;
    private final Color color;

    public Alert(String text, Color color) {
        this.text = text;
        this.color = color;
    }

    @Override
    public String toString() {
        return text;
    }

    @java.lang.SuppressWarnings("all")
    public String getText() {
        return this.text;
    }

    @java.lang.SuppressWarnings("all")
    public Color getColor() {
        return this.color;
    }
}
