// Generated by delombok at Mon Feb 10 12:42:16 CST 2025
package com.eglobal.tools.parser.report;

import com.eglobal.tools.parser.report.dto.Report;
import com.eglobal.tools.parser.report.observer.EventListener;
import com.eglobal.tools.parser.report.observer.EventType;

public class LogFieldParserListener implements EventListener {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(LogFieldParserListener.class);

    @Override
    public void update(EventType eventType, Report data) {
        log.debug("EventType: {} Data: {}", eventType, data);
    }
}
